version: '3.8'
services:
  task-service:
    build: .
    environment:
      - SERVER_PORT=3000
      - TASK_SIMULATED_DURATION=500
      - TASK_SIMULATED_ERROR_PERCENTAGE=20
      - TASK_ERROR_RETRY_DELAY=1000
      - WORKER_TIMEOUT=5000
      - TASK_MAX_RETRIES=3
      - LOG_PATH=/tmp/task_service.log
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/tmp
